
const DEVICE_TOKEN = 'DEVICE_TOKEN';
const DEVICE_ID = 'DEVICE_ID';
const DEVICE_NAME = 'DEVICE_NAME';
const DEVICE_TYPE = 'DEVICE_TYPE';
const APP_VERSION = 'APP_VERSION';
const APP_LANGUAGE = 'APP_LANGUAGE';
const LANGUAGE_UPDATED = 'LANGUAGE_UPDATED';
const LANGUAGE_INDEX = 'LANGUAGE_INDEX';
const CONTENT_ALIGNMENT = 'CONTENT_ALIGNMENT';
const DEVICE_CONNECTION = 'DEVICE_CONNECTION';
const HAS_SESSION = 'HAS_SESSION';
const USER_DETAIL = 'USER_DETAIL';
const USER_CREDENTIALS = 'USER_CREDENTIALS';
const USER_ADDRESS = 'USER_ADDRESS';
const REMEMBER_ME = 'REMEMBER_ME';
const GUEST = 'GUEST';
const LOGOUT = 'LOGOUT';
const RESTART = 'RESTART';
const NOTI_COUNT = 'NOTI_COUNT';
const TODAY_APPOINTMENT = 'TODAY_APPOINTMENT';
const TODAY_CONSULT = 'TODAY_CONSULT';
const TODAY_LAB = 'TODAY_LAB';
const SELECTED_PROVIDER = 'SELECTED_PROVIDER';
const CART = 'CART';
const TABBY_PAYMENT = 'TABBY_PAYMENT'
const USER_PROFILE = 'USER_PROFILE'
const CURRENT_ROUTE = 'CURRENT_ROUTE'


export {
  //
  HAS_SESSION,
  LOGOUT,
  USER_DETAIL,
  DEVICE_TOKEN,
  DEVICE_ID,
  DEVICE_NAME,
  DEVICE_TYPE,
  APP_VERSION,
  APP_LANGUAGE,
  LANGUAGE_UPDATED,
  LANGUAGE_INDEX,
  CONTENT_ALIGNMENT,
  GUEST,
  USER_ADDRESS,
  USER_CREDENTIALS,
  DEVICE_CONNECTION,
  REMEMBER_ME,
  RESTART,
  NOTI_COUNT,
  TODAY_APPOINTMENT,
  TODAY_CONSULT,
  TODAY_LAB,
  SELECTED_PROVIDER,
  CART,
  TABBY_PAYMENT,
  USER_PROFILE,
  CURRENT_ROUTE
};
